pipeline {
    agent any
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Build") {
            steps {
                dir("jenkintest"){
                    sh "mvn clean install"
                }
            }
        }
    }
}